
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab7(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Accelerometer //////////
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [15:0] data_x;
wire [15:0] data_y;
wire clk, spi_clk, spi_clk_out;



//=======================================================
//  Structural coding
//=======================================================

accel proc(
	.ADC_CLK_10 (ADC_CLK_10),
	.MAX10_CLK1_50 (MAX10_CLK1_50),
	.MAX10_CLK2_50 (MAX10_CLK2_50),
	.data_x (data_x),
	.data_y (data_y),
	.KEY (KEY),
	.SW (SW),
	.GSENSOR_CS_N (GSENSOR_CS_N),
	.GSENSOR_INT (GSENSOR_INT),
	.GSENSOR_SCLK (GSENSOR_SCLK),
	.GSENSOR_SDI (GSENSOR_SDI),
	.GSENSOR_SDO (GSENSOR_SDO) );

ip ip_inst (
   .inclk0 ( MAX10_CLK1_50 ),
   .c0 ( clk ),
   .c1 ( spi_clk ),
   .c2 ( spi_clk_out )
   );
	
sub proc3(
	.data_x(data_x),
	.clk(clk),
	.HEX0 (HEX0),
	.HEX1 (HEX1),
	.HEX2 (HEX2),
	.HEX3 (HEX3),
	.HEX4 (HEX4),
	.HEX5 (HEX5),
	.KEY (KEY),
	.LEDR (LEDR),
	.SW (SW) );

endmodule
	
